# 2 - Data Cleaning

In [1]:
import pandas as pd
train_df = pd.read_csv('../data/housing_train.csv')
test_df = pd.read_csv('../data/housing_test.csv')

There is an apparent relation between `MSSubClass` and `HouseStyle`. This is how they should match up:

1Story	One story
- 20	1-STORY 1946 & NEWER ALL STYLES
- 30	1-STORY 1945 & OLDER
- 40	1-STORY W/FINISHED ATTIC ALL AGES
- 120	1-STORY PUD (Planned Unit Development) - 1946 & NEWER

1.5Fin	One and one-half story: 2nd level finished
- 50	1-1/2 STORY FINISHED ALL AGES
- 150	1-1/2 STORY PUD - ALL AGES

1.5Unf	One and one-half story: 2nd level unfinished
- 45	1-1/2 STORY - UNFINISHED ALL AGES

2Story	Two story
- 60	2-STORY 1946 & NEWER
- 70	2-STORY 1945 & OLDER
- 160	2-STORY PUD - 1946 & NEWER


2.5Fin	Two and one-half story: 2nd level finished<br>
2.5Unf	Two and one-half story: 2nd level unfinished
- 75	2-1/2 STORY ALL AGES

SFoyer	Split Foyer
- 85	SPLIT FOYER

SLvl	Split Level
- 80	SPLIT OR MULTI-LEVEL

Misc (No obvious floor number)
- 90	DUPLEX - ALL STYLES AND AGES
- 180	PUD - MULTILEVEL - INCL SPLIT LEV/FOYER
- 190	2 FAMILY CONVERSION - ALL STYLES AND AGES

### Check for mismatches:<p>
Should be one story:

In [2]:
print('Train: \nCode 20\n',train_df[train_df['MSSubClass']==20]['HouseStyle'].value_counts(),'\n')
print('Code 30\n',train_df[train_df['MSSubClass']==30]['HouseStyle'].value_counts(),'\n')
print('Code 40\n',train_df[train_df['MSSubClass']==40]['HouseStyle'].value_counts(),'\n')
print('Code 120\n',train_df[train_df['MSSubClass']==120]['HouseStyle'].value_counts())

Train: 
Code 20
 HouseStyle
1Story    534
2Story      1
SLvl        1
Name: count, dtype: int64 

Code 30
 HouseStyle
1Story    67
1.5Fin     1
1.5Unf     1
Name: count, dtype: int64 

Code 40
 HouseStyle
1Story    4
Name: count, dtype: int64 

Code 120
 HouseStyle
1Story    86
SFoyer     1
Name: count, dtype: int64


Codes 20, 30, 120 have mismatches.

In [6]:
print('Test: \nCode 20\n',test_df[test_df['MSSubClass']==20]['HouseStyle'].value_counts(),'\n')
print('Code 30\n',test_df[test_df['MSSubClass']==30]['HouseStyle'].value_counts(),'\n')
print('Code 40\n',test_df[test_df['MSSubClass']==40]['HouseStyle'].value_counts(),'\n')
print('Code 120\n',test_df[test_df['MSSubClass']==120]['HouseStyle'].value_counts())

Test: 
Code 20
 HouseStyle
1Story    543
Name: count, dtype: int64 

Code 30
 HouseStyle
1Story    69
1.5Fin     1
Name: count, dtype: int64 

Code 40
 HouseStyle
1Story    1
1.5Fin    1
Name: count, dtype: int64 

Code 120
 HouseStyle
1Story    94
SFoyer     1
Name: count, dtype: int64


Codes 30, 40, 120 have mismatches.

Should be 1.5 stories:

In [5]:
print('Train: \nCode 45\n',train_df[train_df['MSSubClass']==45]['HouseStyle'].value_counts(),'\n')
print('Code 50\n',train_df[train_df['MSSubClass']==50]['HouseStyle'].value_counts(),'\n')
print('Code 150\n',train_df[train_df['MSSubClass']==150]['HouseStyle'].value_counts())

Train: 
Code 45
 HouseStyle
1.5Unf    12
Name: count, dtype: int64 

Code 50
 HouseStyle
1.5Fin    141
2Story      3
Name: count, dtype: int64 

Code 150
 Series([], Name: count, dtype: int64)


Code 50 has mismatches, and code 150 is never used.

In [4]:
print('Test: \nCode 45\n',test_df[test_df['MSSubClass']==45]['HouseStyle'].value_counts(),'\n')
print('Code 50\n',test_df[test_df['MSSubClass']==50]['HouseStyle'].value_counts(),'\n')
print('Code 150\n',test_df[test_df['MSSubClass']==150]['HouseStyle'].value_counts())

Test: 
Code 45
 HouseStyle
1.5Unf    4
1.5Fin    2
Name: count, dtype: int64 

Code 50
 HouseStyle
1.5Fin    141
1.5Unf      1
2Story      1
Name: count, dtype: int64 

Code 150
 HouseStyle
1.5Fin    1
Name: count, dtype: int64


Code 50 has a mismatch again, as does 45.

Should be 2 stories:

In [3]:
print('Train: \nCode 60\n',train_df[train_df['MSSubClass']==60]['HouseStyle'].value_counts(),'\n')
print('Code 70\n',train_df[train_df['MSSubClass']==70]['HouseStyle'].value_counts(),'\n')
print('Code 160\n',train_df[train_df['MSSubClass']==160]['HouseStyle'].value_counts())

Train: 
Code 60
 HouseStyle
2Story    298
SLvl        1
Name: count, dtype: int64 

Code 70
 HouseStyle
2Story    59
2.5Fin     1
Name: count, dtype: int64 

Code 160
 HouseStyle
2Story    63
Name: count, dtype: int64


Code 70 has a mismatch. Code 60 could, but as a split level is just a special style of multistory house, I'm going to leave it. There's no way to know if it's a two level split or more.

In [9]:
print('Test: \nCode 60\n',test_df[test_df['MSSubClass']==60]['HouseStyle'].value_counts(),'\n')
print('Code 70\n',test_df[test_df['MSSubClass']==70]['HouseStyle'].value_counts(),'\n')
print('Code 160\n',test_df[test_df['MSSubClass']==160]['HouseStyle'].value_counts())

Test: 
Code 60
 HouseStyle
2Story    274
1.5Fin      1
2.5Unf      1
Name: count, dtype: int64 

Code 70
 HouseStyle
2Story    64
2.5Unf     3
1.5Fin     1
Name: count, dtype: int64 

Code 160
 HouseStyle
2Story    64
SLvl       1
Name: count, dtype: int64


Codes 60 and 70 have mismatches, and the split level on 160 I am going to leave. 

Should be 2.5 stories:

In [8]:
print('Train: \nCode 75\n',train_df[train_df['MSSubClass']==75]['HouseStyle'].value_counts(),'\n')
print('Test: \nCode 75\n',test_df[test_df['MSSubClass']==75]['HouseStyle'].value_counts())

Train: 
Code 75
 HouseStyle
2.5Unf    9
2.5Fin    6
2Story    1
Name: count, dtype: int64 

Test: 
Code 75
 HouseStyle
2.5Unf    6
2Story    1
Name: count, dtype: int64


Both train and test have mismatches on code 75.

Should be split foyer:

In [7]:
print('Code 85\n',train_df[train_df['MSSubClass']==85]['HouseStyle'].value_counts(),'\n')
print('Code 85\n',test_df[test_df['MSSubClass']==85]['HouseStyle'].value_counts())

Code 85
 HouseStyle
SFoyer    20
Name: count, dtype: int64 

Code 85
 HouseStyle
SFoyer    28
Name: count, dtype: int64


No mismatches.

Should be split level:

In [11]:
print('Code 80\n',train_df[train_df['MSSubClass']==80]['HouseStyle'].value_counts(),'\n')
print('Code 80\n',test_df[test_df['MSSubClass']==80]['HouseStyle'].value_counts())

Code 80
 HouseStyle
SLvl    58
Name: count, dtype: int64 

Code 80
 HouseStyle
SLvl    60
Name: count, dtype: int64


No mismatches.

### Fixing mismatches <p>
In the train set

In [10]:
# setting 1 story
# Code 20
train_df.loc[((train_df[ # select
    (train_df['MSSubClass']==20)& # code 20 AND either
    ((train_df['HouseStyle']=='2Story')| # 2 Story OR
     (train_df['HouseStyle']=='SLvl'))   # Split Level
    ].index).tolist()), 'HouseStyle'] = '1Story'

# Code 30
train_df.loc[((train_df[ # select
    (train_df['MSSubClass']==30)& # code 30 AND either
    ((train_df['HouseStyle']=='1.5Fin')| # 1.5 Finished OR
     (train_df['HouseStyle']=='1.5Unf')) # 1.5 Unfinished
].index).tolist()), 'HouseStyle'] = '1Story'

# Code 120
train_df.loc[((train_df[ # select
    (train_df['MSSubClass']==120)& # code 120 AND
    (train_df['HouseStyle']=='SFoyer') # split foyer
].index).tolist()), 'HouseStyle'] = '1Story'

In [12]:
print('Check: \nCode 20\n',train_df[train_df['MSSubClass']==20]['HouseStyle'].value_counts(),'\n')
print('Code 30\n',train_df[train_df['MSSubClass']==30]['HouseStyle'].value_counts(),'\n')
print('Code 120\n',train_df[train_df['MSSubClass']==120]['HouseStyle'].value_counts())

Check: 
Code 20
 HouseStyle
1Story    536
Name: count, dtype: int64 

Code 30
 HouseStyle
1Story    69
Name: count, dtype: int64 

Code 120
 HouseStyle
1Story    87
Name: count, dtype: int64


In [13]:
# setting 1.5Fin story, Code 50
train_df.loc[((train_df[ # select
    (train_df['MSSubClass']==50)& # code 50 AND
    (train_df['HouseStyle']=='2Story') # 2 story
].index).tolist()), 'HouseStyle'] = '1.5Fin'

In [14]:
print('Check: \nCode 50\n',train_df[train_df['MSSubClass']==50]['HouseStyle'].value_counts())

Check: 
Code 50
 HouseStyle
1.5Fin    144
Name: count, dtype: int64


In [15]:
# setting 2 stories
# Code 70
train_df.loc[((train_df[ # select
    (train_df['MSSubClass']==70)& # code 70 AND
    (train_df['HouseStyle']=='2.5Fin') # 2.5 finished
].index).tolist()), 'HouseStyle'] = '2Story'

In [16]:
print('Check: \nCode 70\n',train_df[train_df['MSSubClass']==70]['HouseStyle'].value_counts())

Check: 
Code 70
 HouseStyle
2Story    60
Name: count, dtype: int64


For the 2.5 story code, 75, there is no way to tell if they are meant to be finished or unfinished. As they only have one code, and there are not very many of them, even when the test data is included, I am going to code them all as simply `2.5Story`.

In [17]:
# setting 2.5 stories, code 75
train_df.loc[((train_df[train_df['MSSubClass']==75].index).tolist()), 'HouseStyle'] = '2.5Story'

In [18]:
print('Check: \nCode 75\n',train_df[train_df['MSSubClass']==75]['HouseStyle'].value_counts())

Check: 
Code 75
 HouseStyle
2.5Story    16
Name: count, dtype: int64


In the test set

In [19]:
# setting 1 story
# Code 30
test_df.loc[((test_df[ # select
    (test_df['MSSubClass']==30)& # code 30 AND
    (test_df['HouseStyle']=='1.5Fin') # 1.5 finished
].index).tolist()), 'HouseStyle'] = '1Story'

# Code 40
test_df.loc[((test_df[ # select
    (test_df['MSSubClass']==40)& # code 40 AND
    (test_df['HouseStyle']=='1.5Fin') # 1.5 finished
].index).tolist()), 'HouseStyle'] = '1Story'

# Code 120
test_df.loc[((test_df[ # select
    (test_df['MSSubClass']==120)& # code 120 AND
    (test_df['HouseStyle']=='SFoyer') # split foyer
].index).tolist()), 'HouseStyle'] = '1Story'

In [20]:
print('Check: \nCode 30\n',test_df[test_df['MSSubClass']==30]['HouseStyle'].value_counts(),'\n')
print('Code 40\n',test_df[test_df['MSSubClass']==40]['HouseStyle'].value_counts(),'\n')
print('Code 120\n',test_df[test_df['MSSubClass']==120]['HouseStyle'].value_counts())

Check: 
Code 30
 HouseStyle
1Story    70
Name: count, dtype: int64 

Code 40
 HouseStyle
1Story    2
Name: count, dtype: int64 

Code 120
 HouseStyle
1Story    95
Name: count, dtype: int64


In [22]:
# setting 1.5Unf, Code 45
test_df.loc[((test_df[ # select
    (test_df['MSSubClass']==45)& # code 45 AND
    (test_df['HouseStyle']=='1.5Fin') # 1.5 finished
].index).tolist()), 'HouseStyle'] = '1.5Unf'

# setting 1.5Fin story, Code 50
test_df.loc[((test_df[ # select
    (test_df['MSSubClass']==50)& # code 50 AND either
    ((test_df['HouseStyle']=='1.5Unf')| # 1.5 Unfinished OR
    (test_df['HouseStyle']=='2Story')) # 2 story
].index).tolist()), 'HouseStyle'] = '1.5Fin'

In [23]:
print('Test \nCode 45\n',test_df[test_df['MSSubClass']==45]['HouseStyle'].value_counts(),'\n')
print('Code 50\n',test_df[test_df['MSSubClass']==50]['HouseStyle'].value_counts())

Test 
Code 45
 HouseStyle
1.5Unf    6
Name: count, dtype: int64 

Code 50
 HouseStyle
1.5Fin    143
Name: count, dtype: int64


In [21]:
# setting 2 stories
# Code 60
test_df.loc[((test_df[ # select
    (test_df['MSSubClass']==60)& # code 60 AND either
    ((test_df['HouseStyle']=='1.5Fin')| # 1.5 finished OR
    (test_df['HouseStyle']=='2.5Unf')) # 2.5 unfinished
].index).tolist()), 'HouseStyle'] = '2Story'

# Code 70
test_df.loc[((test_df[ # select
    (test_df['MSSubClass']==70)& # code 70 AND either
    ((test_df['HouseStyle']=='1.5Fin')| # 1.5 finished OR
    (test_df['HouseStyle']=='2.5Unf')) # 2.5 unfinished
].index).tolist()), 'HouseStyle'] = '2Story'

In [24]:
print('Test: \nCode 60\n',test_df[test_df['MSSubClass']==60]['HouseStyle'].value_counts(),'\n')
print('Code 70\n',test_df[test_df['MSSubClass']==70]['HouseStyle'].value_counts())

Test: 
Code 60
 HouseStyle
2Story    276
Name: count, dtype: int64 

Code 70
 HouseStyle
2Story    68
Name: count, dtype: int64


In [25]:
# setting 2.5 stories, code 75
test_df.loc[((test_df[test_df['MSSubClass']==75].index).tolist()), 'HouseStyle'] = '2.5Story'

In [26]:
print('Check: \nCode 75\n',test_df[test_df['MSSubClass']==75]['HouseStyle'].value_counts())

Check: 
Code 75
 HouseStyle
2.5Story    7
Name: count, dtype: int64


Functional: Home functionality (Assume typical unless deductions are warranted)

       Typ	Typical Functionality
       Min1	Minor Deductions 1
       Min2	Minor Deductions 2
       Mod	Moderate Deductions
       Maj1	Major Deductions 1
       Maj2	Major Deductions 2
       Sev	Severely Damaged
       Sal	Salvage only

Fill missing values in test w/ Typ

In [ ]:
print(test_df['Functional'].isna().value_counts(),'\n')
print(test_df[test_df['Functional'].isna()][['Functional']])

In [ ]:
print(test_df['SaleType'].isna().value_counts(),'\n')
print(test_df[test_df['SaleType'].isna()][['SaleType','SaleCondition','YearBuilt','YrSold']],'\n')
print(f'Train: {train_df[train_df['SaleCondition']=='Normal'][['SaleType','SaleCondition']].value_counts()} \n')
print(f'Test: {test_df[test_df['SaleCondition']=='Normal'][['SaleType','SaleCondition']].value_counts()}')

I could delete this row, but if I want to keep it, it is probably safe to fill in the `SaleType` with 'WD', as for a `SaleCondition` of 'Normal', the vast majority of datapoints have have value. (96.8% for train, 95.9% for test.)

In [ ]:
print(train_df['Electrical'].isna().value_counts(),'\n')
print(train_df[train_df['Electrical'].isna()][['Electrical','YearBuilt']],'\n')

In [ ]:
print(f'Train: {train_df['Electrical'].value_counts()},\n')
print(f'Test: {test_df['Electrical'].value_counts()} \n')
print(train_df[train_df['Electrical']=='SBrkr'][['Electrical','YearBuilt']].describe())

Similarly, the vast majority of data (91.4% of train, 91.6% of test) has the 'SBrkr' value, and the descriptive stats show there is no meaningful connection between building age and electrical status to worry about, so again it is probably safe to use that value in the interest of keeping the row in. 

Utilities: Type of utilities available
		
       AllPub	All public Utilities (E,G,W,& S)	
       NoSewr	Electricity, Gas, and Water (Septic Tank)
       NoSeWa	Electricity and Gas Only
       ELO	Electricity only

### Remove outliers<p>
Using thresholds from previous notebook.

In [ ]:
train_df[train_df['LotFrontage']>250]

In [ ]:
train_df[train_df['LotArea']>140000]

In [ ]:
train_df[train_df['BsmtFinSF1']>4000]

In [ ]:
train_df[train_df['BsmtFinSF2']>1300]

In [ ]:
train_df[train_df['TotalBsmtSF']>5000]

In [ ]:
train_df[train_df['1stFlrSF']>4000]

In [ ]:
train_df[train_df['GrLivArea']>5000]

In [ ]:
train_df[train_df['EnclosedPorch']>500]

In [ ]:
train_df[train_df['MiscVal']>6000]

In [ ]:
train_df[train_df['SalePrice']>700000]